name: Build hanwckf's Padavan

on: 
  workflow_dispatch:
    inputs:
      model:
        description: 'choose your device model'
        default: 'MR2600-5.0'

env:
  TNAME: ${{ github.event.inputs.model }}

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo apt update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      run: |
        TNAME="${{ github.event.inputs.model }}" 
        #通用修改storage空间大小
        # cd /opt/rt-n56u/trunk/configs/boards/型号
        # sed -i 's/CONFIG_MTD_STORE_PART_SIZ=0x200000/CONFIG_MTD_STORE_PART_SIZ=0x80000/g' kernel-3.4.x-5.0.config #0x200000是2MB 0x80000是512KB
        # cd /opt/rt-n56u/trunk/configs/boards/XY-C1
        # sed -i 's/CONFIG_MTD_STORE_PART_SIZ=0x200000/CONFIG_MTD_STORE_PART_SIZ=0xC00000/g' kernel-3.4.x.config #0x200000是2MB 0x80000是512KB 0xC00000是12MB
        #通用修改storage空间大小
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config temp.config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' temp.config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        #忽略所有校园网客户端，一般家用不需要这东西。
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' temp.config #删除配置项 MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_GDUT_DRCOM/d' temp.config #删除配置项 GDUT_DRCOM
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' temp.config #删除配置项 SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' temp.config #删除配置项 DOGCOM
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' temp.config #删除配置项 NJIT_CLIENT
        #忽略所有校园网客户端，一般家用不需要这东西。
        sed -i '/CONFIG_FIRMWARE_INCLUDE_UVC/d' temp.config #删除配置项 UVC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_AUDIO/d' temp.config #删除配置项 AUDIO
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIDLNA/d' temp.config #删除配置项 MINIDLNA
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' temp.config #删除配置项 TRANSMISSION
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' temp.config #删除配置项 TRANSMISSION_WEB_CONTROL
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' temp.config #删除配置项 ARIA
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' temp.config #删除配置项 ARIA_WEB_CONTROL
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' temp.config #删除配置项 NAPT66
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' temp.config #删除配置项 SHADOWSOCKS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' temp.config #删除配置项 SSSERVER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' temp.config #删除配置项 SOFTETHERVPN_SERVER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' temp.config #删除配置项 SOFTETHERVPN_CLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' temp.config #删除配置项 SOFTETHERVPN_CMD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' temp.config #删除配置项 DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' temp.config #删除配置项 VLMCSD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TTYD/d' temp.config #删除配置项 TTYD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LRZSZ/d' temp.config #删除配置项 LRZSZ
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' temp.config #删除配置项 HTOP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' temp.config #删除配置项 NANO
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' temp.config #删除配置项 IPERF3
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DUMP1090/d' temp.config #删除配置项 DUMP1090
        sed -i '/CONFIG_FIRMWARE_INCLUDE_RTL_SDR/d' temp.config #删除配置项 RTL_SDR
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' temp.config #删除配置项 MTR
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' temp.config #删除配置项 SRELAY
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' temp.config #删除配置项 FRPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' temp.config #删除配置项 FRPS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' temp.config #删除配置项 TUNSAFE
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WIREGUARD/d' temp.config #删除配置项 WIREGUARD
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        #忽略所有校园网客户端，一般家用不需要这东西，如果你需要自行选上对应的程序。
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> temp.config #MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_GDUT_DRCOM=n" >> temp.config #GDUT_DRCOM
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> temp.config #SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> temp.config #DOGCOM
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> temp.config #NJIT_CLIENT
        #忽略所有校园网客户端，一般家用不需要这东西，如果你需要自行选上对应的程序。
        echo "CONFIG_FIRMWARE_INCLUDE_UVC=n" >> temp.config #UVC
        echo "CONFIG_FIRMWARE_INCLUDE_AUDIO=n" >> temp.config #AUDIO
        echo "CONFIG_FIRMWARE_INCLUDE_MINIDLNA=n" >> temp.config #MINIDLNA
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION=n" >> temp.config #TRANSMISSION
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL=n" >> temp.config #TRANSMISSION_WEB_CONTROL
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA=n" >> temp.config #ARIA
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL=n" >> temp.config #ARIA_WEB_CONTROL
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> temp.config #NAPT66
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> temp.config #SHADOWSOCKS
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=y" >> temp.config #SSSERVER
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> temp.config #SOFTETHERVPN_SERVER
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> temp.config #SOFTETHERVPN_CLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> temp.config #SOFTETHERVPN_CMD
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=y" >> temp.config #DNSFORWARDER
        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=y" >> temp.config #VLMCSD
        echo "CONFIG_FIRMWARE_INCLUDE_TTYD=y" >> temp.config #TTYD
        echo "CONFIG_FIRMWARE_INCLUDE_LRZSZ=y" >> temp.config #LRZSZ
        echo "CONFIG_FIRMWARE_INCLUDE_HTOP=y" >> temp.config #HTOP
        echo "CONFIG_FIRMWARE_INCLUDE_NANO=y" >> temp.config #NANO
        echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=n" >> temp.config #IPERF3
        echo "CONFIG_FIRMWARE_INCLUDE_DUMP1090=n" >> temp.config #DUMP1090
        echo "CONFIG_FIRMWARE_INCLUDE_RTL_SDR=n" >> temp.config #RTL_SDR
        echo "CONFIG_FIRMWARE_INCLUDE_MTR=y" >> temp.config #MTR
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> temp.config #SRELAY
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> temp.config #FRPC
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> temp.config #FRPS
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> temp.config #TUNSAFE
        echo "CONFIG_FIRMWARE_INCLUDE_WIREGUARD=n" >> temp.config #WIREGUARD
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' temp.config
        #echo "自定义项=y" >> temp.config
        #########################################################################################
        cp -f temp.config configs/templates/$TNAME.config
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME
        sudo mv -f configs/templates/$TNAME.config /opt/images/
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: ${{ env.TNAME }} Firmware	
        path: /opt/images
