name: Build chongshengB's Padavan

on: 
  workflow_dispatch:
    inputs:
      model:
        description: 'choose your device model'
        default: 'MR2600-5.0'

env:
  TNAME: ${{ github.event.inputs.model }}

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      run: |
        #通用修改storage空间大小
        # cd /opt/rt-n56u/trunk/configs/boards/型号
        # sed -i 's/CONFIG_MTD_STORE_PART_SIZ=0x200000/CONFIG_MTD_STORE_PART_SIZ=0x80000/g' kernel-3.4.x-5.0.config #0x200000是2MB 0x80000是512KB
        # cd /opt/rt-n56u/trunk/configs/boards/XY-C1
        # sed -i 's/CONFIG_MTD_STORE_PART_SIZ=0x200000/CONFIG_MTD_STORE_PART_SIZ=0xC00000/g' kernel-3.4.x.config #0x200000是2MB 0x80000是512KB 0xC00000是12MB
        #通用修改storage空间大小
        #关掉miniupnpd的V6和IGDv2，否则Windows设备用不了
        cd /opt/rt-n56u/trunk/user/miniupnpd
        sed -i 's/ENABLE_IPV6:=1/ENABLE_IPV6:=0/g' Makefile
        sed -i 's/genconfig.sh --ipv6 --igd2/genconfig.sh/g' Makefile
        #关掉miniupnpd的V6和IGDv2，否则Windows设备用不了
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        #忽略所有校园网客户端，一般家用不需要这东西。
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项 MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_GDUT_DRCOM/d' .config #删除配置项 GDUT_DRCOM
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项 SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config #删除配置项 DOGCOM
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config #删除配置项 NJIT_CLIENT
        #忽略所有校园网客户端，一般家用不需要这东西。
        sed -i '/CONFIG_FIRMWARE_INCLUDE_UVC/d' .config #删除配置项 UVC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_AUDIO/d' .config #删除配置项 AUDIO
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIDLNA/d' .config #删除配置项 MINIDLNA
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config #删除配置项 TRANSMISSION
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' .config #删除配置项 TRANSMISSION_WEB_CONTROL
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' .config #删除配置项 ARIA
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' .config #删除配置项 ARIA_WEB_CONTROL
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config #删除配置项 NAPT66
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项 SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSOBFS/d' .config #删除配置项 simple-obfs混淆插件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项 SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config #删除配置项 SOFTETHERVPN_SERVER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config #删除配置项 SOFTETHERVPN_CLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config #删除配置项 SOFTETHERVPN_CMD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项 DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' .config #删除配置项 VLMCSD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TTYD/d' .config #删除配置项 TTYD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LRZSZ/d' .config #删除配置项 LRZSZ
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' .config #删除配置项 HTOP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' .config #删除配置项 NANO
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' .config #删除配置项 IPERF3
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DUMP1090/d' .config #删除配置项 DUMP1090
        sed -i '/CONFIG_FIRMWARE_INCLUDE_RTL_SDR/d' .config #删除配置项 RTL_SDR
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' .config #删除配置项 MTR
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config #删除配置项 SRELAY
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项 FRPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项 FRPS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项 TUNSAFE
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WIREGUARD/d' .config #删除配置项 WIREGUARD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项 adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #删除配置项 阿里DDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config #删除配置项 smartdns
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN/d' .config #删除配置项 smartdns二进制文件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_V2RAY/d' .config #删除配置项 集成v2ray执行文件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TROJAN/d' .config #删除配置项 集成trojan执行文件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_KOOLPROXY/d' .config #删除配置项 KP广告过滤
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CADDY/d' .config #删除配置项 在线文件管理服务
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CADDYBIN/d' .config #删除配置项 集成caddu执行文件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME/d' .config #删除配置项 ADGH广告过滤
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WYY/d' .config #删除配置项 网易云解锁
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WYYBIN/d' .config #删除配置项 网易云解锁GO版本执行文件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config #删除配置项 zerotier
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        #忽略所有校园网客户端，一般家用不需要这东西，如果你需要自行选上对应的程序。
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_GDUT_DRCOM=n" >> .config #GDUT_DRCOM
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config #DOGCOM
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config #NJIT_CLIENT
        #忽略所有校园网客户端，一般家用不需要这东西，如果你需要自行选上对应的程序。
        echo "CONFIG_FIRMWARE_INCLUDE_UVC=n" >> .config #UVC
        echo "CONFIG_FIRMWARE_INCLUDE_AUDIO=n" >> .config #AUDIO
        echo "CONFIG_FIRMWARE_INCLUDE_MINIDLNA=n" >> .config #MINIDLNA
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION=n" >> .config #TRANSMISSION
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL=n" >> .config #TRANSMISSION_WEB_CONTROL
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA=n" >> .config #ARIA
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL=n" >> .config #ARIA_WEB_CONTROL
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config #NAPT66
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config # simple-obfs混淆插件
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config #SOFTETHERVPN_SERVER
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config #SOFTETHERVPN_CLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config #SOFTETHERVPN_CMD
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=y" >> .config #VLMCSD
        echo "CONFIG_FIRMWARE_INCLUDE_TTYD=y" >> .config #TTYD
        echo "CONFIG_FIRMWARE_INCLUDE_LRZSZ=y" >> .config #LRZSZ
        echo "CONFIG_FIRMWARE_INCLUDE_HTOP=y" >> .config #HTOP
        echo "CONFIG_FIRMWARE_INCLUDE_NANO=y" >> .config #NANO
        echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=n" >> .config #IPERF3
        echo "CONFIG_FIRMWARE_INCLUDE_DUMP1090=n" >> .config #DUMP1090
        echo "CONFIG_FIRMWARE_INCLUDE_RTL_SDR=n" >> .config #RTL_SDR
        echo "CONFIG_FIRMWARE_INCLUDE_MTR=y" >> .config #MTR
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #SRELAY
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #FRPC
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #FRPS
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
        echo "CONFIG_FIRMWARE_INCLUDE_WIREGUARD=n" >> .config #WIREGUARD
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> .config #adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #阿里DDNS
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=y" >> .config #smartdns二进制文件
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KP广告过滤
        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #在线文件管理服务
        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config #ADGH广告过滤
        echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #网易云解锁
        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #网易云解锁GO版本执行文件（4M多）注意固件超大小,不集成会自动下载
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config #zerotier ~1.3M
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        sudo ./clear_tree
        fakeroot ./build_firmware_modify $TNAME 0
        sudo mv -f configs/templates/$TNAME.config /opt/images/
        sudo mv -f .config /opt/images/
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: ${{ env.TNAME }} Firmware	
        path: /opt/images
